#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MYSQL_CONTAINER="${MYSQL_CONTAINER:-local-fresh-backend-mysql}"
DATABASE_NAME="${DATABASE_NAME:-bytebites_migration_smoke_$(date +%Y%m%d%H%M%S)_$$}"
JAVA_PORT="${JAVA_PORT:-18081}"
TIMEOUT_SECONDS="${TIMEOUT_SECONDS:-120}"
KEEP_DATABASE="${KEEP_DATABASE:-false}"
DRY_RUN="${DRY_RUN:-false}"
LOG_FILE="${LOG_FILE:-}"
JAVA_PID=""

usage() {
  cat <<'USAGE'
Usage: scripts/smoke-clean-mysql-migrations.sh [options]

Runs the Java backend against a temporary clean MySQL database to prove
Flyway migrations can bootstrap a fresh schema. The temporary database is
dropped by default when the check exits.

The live smoke expects the usual backend dependencies to be reachable by
the Java app, including Redis and RabbitMQ. The script owns only the
temporary MySQL database and Java process it starts.

Options:
  --mysql-container NAME   Docker MySQL container. Default: local-fresh-backend-mysql
  --database NAME          Temporary database name. Default: generated bytebites_migration_smoke_*
  --java-port PORT         Temporary Java server port. Default: 18081
  --timeout SECONDS        Health wait timeout. Default: 120
  --keep-database          Do not drop the temporary database on exit.
  --dry-run                Print planned actions without Docker, MySQL, or Java calls.
  -h, --help               Show this help.

Environment:
  MYSQL_CONTAINER
  DATABASE_NAME
  JAVA_PORT
  TIMEOUT_SECONDS
  KEEP_DATABASE
  DRY_RUN
  LOG_FILE
USAGE
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --mysql-container)
      if [ "$#" -lt 2 ]; then
        printf "%s\n" "--mysql-container requires a name" >&2
        usage >&2
        exit 2
      fi
      MYSQL_CONTAINER="$2"
      shift 2
      ;;
    --database)
      if [ "$#" -lt 2 ]; then
        printf "%s\n" "--database requires a name" >&2
        usage >&2
        exit 2
      fi
      DATABASE_NAME="$2"
      shift 2
      ;;
    --java-port)
      if [ "$#" -lt 2 ]; then
        printf "%s\n" "--java-port requires a port" >&2
        usage >&2
        exit 2
      fi
      JAVA_PORT="$2"
      shift 2
      ;;
    --timeout)
      if [ "$#" -lt 2 ]; then
        printf "%s\n" "--timeout requires seconds" >&2
        usage >&2
        exit 2
      fi
      TIMEOUT_SECONDS="$2"
      shift 2
      ;;
    --keep-database)
      KEEP_DATABASE=true
      shift
      ;;
    --dry-run)
      DRY_RUN=true
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      printf "unknown option: %s\n" "$1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if [[ ! "$DATABASE_NAME" =~ ^[A-Za-z0-9_]+$ ]]; then
  printf "database name must contain only letters, numbers, and underscores: %s\n" "$DATABASE_NAME" >&2
  exit 2
fi

if [[ ! "$JAVA_PORT" =~ ^[0-9]+$ ]]; then
  printf "java port must be numeric: %s\n" "$JAVA_PORT" >&2
  exit 2
fi

if [[ ! "$TIMEOUT_SECONDS" =~ ^[0-9]+$ ]]; then
  printf "timeout must be numeric: %s\n" "$TIMEOUT_SECONDS" >&2
  exit 2
fi

mysql_exec() {
  local sql="$1"
  docker exec -e SQL="$sql" "$MYSQL_CONTAINER" sh -c \
    'mysql -uroot -p"$MYSQL_ROOT_PASSWORD" -e "$SQL"'
}

cleanup() {
  local code=$?
  if [ -n "$JAVA_PID" ] && kill -0 "$JAVA_PID" >/dev/null 2>&1; then
    kill "$JAVA_PID" >/dev/null 2>&1 || true
    wait "$JAVA_PID" >/dev/null 2>&1 || true
  fi
  if [ "$KEEP_DATABASE" != "true" ] && [ "$DRY_RUN" != "true" ]; then
    mysql_exec "DROP DATABASE IF EXISTS \`$DATABASE_NAME\`;" >/dev/null 2>&1 || true
  fi
  if [ "$code" -ne 0 ]; then
    printf "clean MySQL migration smoke failed; Java log: %s\n" "$LOG_FILE" >&2
    if [ -f "$LOG_FILE" ]; then
      tail -n 80 "$LOG_FILE" >&2 || true
    fi
  fi
  exit "$code"
}
trap cleanup EXIT INT TERM

if [ "$DRY_RUN" = "true" ]; then
  DISPLAY_LOG_FILE="${LOG_FILE:-<auto temporary log>}"
  cat <<DRYRUN
Clean MySQL migration smoke dry run
mysql_container=$MYSQL_CONTAINER
database_name=$DATABASE_NAME
java_port=$JAVA_PORT
timeout_seconds=$TIMEOUT_SECONDS
keep_database=$KEEP_DATABASE
log_file=$DISPLAY_LOG_FILE

Checks:
1. Verify Docker and the MySQL container are reachable.
2. Create a temporary clean MySQL database.
3. Start Java with MYSQL_DATABASE=$DATABASE_NAME and SERVER_PORT=$JAVA_PORT.
4. Wait for /actuator/health to return UP.
5. Stop Java and drop the temporary database unless --keep-database is set.
DRYRUN
  exit 0
fi

if [ -z "$LOG_FILE" ]; then
  LOG_FILE="$(mktemp "${TMPDIR:-/tmp}/bytebites-clean-migration.XXXXXX")"
fi

printf "ByteBites clean MySQL migration smoke\n"
printf "mysql_container=%s\n" "$MYSQL_CONTAINER"
printf "database_name=%s\n" "$DATABASE_NAME"
printf "java_port=%s\n" "$JAVA_PORT"
printf "log_file=%s\n" "$LOG_FILE"

if ! command -v docker >/dev/null 2>&1; then
  printf "docker command not found\n" >&2
  exit 1
fi

if [ "$(docker inspect -f '{{.State.Running}}' "$MYSQL_CONTAINER" 2>/dev/null || true)" != "true" ]; then
  printf "MySQL container is not running: %s\n" "$MYSQL_CONTAINER" >&2
  exit 1
fi

if lsof -nP -iTCP:"$JAVA_PORT" -sTCP:LISTEN >/dev/null 2>&1; then
  printf "port %s is already in use\n" "$JAVA_PORT" >&2
  exit 1
fi

mysql_exec "DROP DATABASE IF EXISTS \`$DATABASE_NAME\`; CREATE DATABASE \`$DATABASE_NAME\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;" >/dev/null

(
  cd "$ROOT_DIR/backend-java"
  set -a
  [ -f .env ] && source .env
  set +a
  env MYSQL_DATABASE="$DATABASE_NAME" \
    SERVER_PORT="$JAVA_PORT" \
    TAPPAY_PARTNER_KEY="${TAPPAY_PARTNER_KEY:-test}" \
    TAPPAY_MERCHANT_CREDITCARD="${TAPPAY_MERCHANT_CREDITCARD:-test}" \
    mvn spring-boot:run
) >"$LOG_FILE" 2>&1 &
JAVA_PID=$!

deadline=$((SECONDS + TIMEOUT_SECONDS))
while [ "$SECONDS" -lt "$deadline" ]; do
  health_body="$(curl -fsS --max-time 5 "http://127.0.0.1:$JAVA_PORT/actuator/health" 2>/dev/null || true)"
  if printf "%s" "$health_body" | grep -Fq '"UP"'; then
    printf "PASS Java booted from clean MySQL schema and health is UP.\n"
    exit 0
  fi
  if ! kill -0 "$JAVA_PID" >/dev/null 2>&1; then
    printf "Java process exited before health became UP.\n" >&2
    exit 1
  fi
  sleep 2
done

printf "Timed out waiting for Java health on port %s.\n" "$JAVA_PORT" >&2
exit 1
